---
title: "CCA Y RDA"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

## Figurs 6 and 7: cca
- Loading packages and data
```{r, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = T, results = "hide")
library(reshape2)
library(tidyverse)
library(picante)
library(Rmisc)
library(readxl)
library(vegan)
library(qiime2R)
source("../Code/functions_betadiv.R")

#Environmental data
metadata_secas<- read_excel("../Data/Metadatos.xlsx", sheet = "secas-marzo")
fq_secas<- read_excel("../Data/fisicoq.xlsx", sheet = "seca")
fq_secas2<- read.csv("../Data/fisicoq-la.csv")
meta_fq_secas<- metadata_secas %>% full_join(fq_secas) 
meta_fq_secas_all<- metadata_secas %>% full_join(fq_secas) %>% full_join(fq_secas2, by = "SampleID")
env<-meta_fq_secas_all

metadata<-read_excel("../Data/Metadatos.xlsx") %>% mutate_if(is.numeric, as.factor)


# Vegetation data

veg<- read_tsv("../Data/vegeta.tsv") %>% as.data.frame( ) %>% 
   select_all(~str_replace(., "prop_", ""))  %>% 
   select_all(~str_replace(., "mean_", ""))  %>% 
   select_all(~str_replace(., "coverage_", "cov_")) %>% mutate(SampleID=case_when(
  SampleID=="P6S1T1" ~"P6S2T1",
  SampleID=="P6S1T2" ~"P6S2T2",
  SampleID=="P6S1T3" ~"P6S2T3",
  SampleID=="P6S2T1" ~"P6S1T1",
  SampleID=="P6S2T2" ~"P6S1T2",
  SampleID=="P6S2T3" ~"P6S1T3",
  TRUE~as.character(SampleID))) %>% arrange(SampleID)

# Metagenomic data

table_single<-read.delim("../Data/table_micop_single.txt") 
table_paired<-read.delim("../Data/table_micop_paired.txt") 
table_kraken<-read.delim("../Data/table_fungi_again.txt", 
                   skip = 1,
                   row.names = 1, check.names = F) %>% dplyr::select_if(
                     is.numeric)%>% t() %>% as.data.frame() %>% rownames_to_column(var = "id_sequence") %>% separate(
                         ., "id_sequence", c(
                           "kraken", "fungi", 
                           "id_metagenome", "report", "bracken"), 
                         sep = "_") %>% dplyr::select(
                           -kraken, -fungi, -report, -bracken) %>% full_join(
                           metadata) %>% dplyr::select(-id_sequence:-Transecto, -id_metagenome, -Sites, -id_new, -Names,  -id_fisicoq) %>% column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)

table_qiime2<-data.frame(read_qza("../Data/clustered_table_filter.qza")$data, 
                   check.names = F) %>% t() %>% as.data.frame(
                   ) %>% rownames_to_column(
                     var = "SampleID") %>% separate(
                       SampleID, c(
                         "id_metagenome", "R", "unmap", "Paired"), 
                       sep = "_")%>% inner_join(
                         metadata) %>% dplyr::select(
                           -id_metagenome:-Paired, 
                           -id_sequence:-id_fisicoq, -Sites, 
                           -Names) %>% column_to_rownames(
                             var="SampleID") %>% t(
                             ) %>% as.data.frame() %>% mutate_all(as.numeric)



table_qiime2_t<-data.frame(t(table_qiime2), check.names = F)
table_single_t<-data.frame(t(table_single), check.names = F)
table_paired_t<-data.frame(t(table_paired), check.names = F)
table_kraken_t<-data.frame(t(table_kraken), check.names = F)
```

- Environmental analysis
```{r, warning=FALSE, message=FALSE}

#select variables that did not show collinearity and order data
set.seed(124)
vars<- c("MO", "Ca", "LIMO", "ARCILLA", "WHC", "Fe", "K", "Mg",
         "pH", "Cu", "P", "N", "moisture")

#qiime2
mm1<-table_qiime2_t %>% rownames_to_column(var = "SampleID") %>% inner_join(
  env) %>% column_to_rownames(var = "SampleID")
env1=mm1[,vars]
#env1=mm1[,c(3149:3159, 3162,  3165,3167)]
spp1=mm1[,1:3138]

#single
mm2<-table_single_t %>% rownames_to_column(var = "SampleID") %>% inner_join(
  env) %>% column_to_rownames(var = "SampleID")
env2=mm2[,vars]
spp2=mm2[,1:210]

#paired
mm3<-table_paired_t %>% rownames_to_column(var = "SampleID") %>% inner_join(
  env) %>% column_to_rownames(var = "SampleID")
env3=mm3[,vars]
spp3=mm3[,1:234]

#kraken
mm4<-table_kraken_t %>% rownames_to_column(var = "SampleID") %>% inner_join(
  env) %>% column_to_rownames(var = "SampleID")
env4=mm4[,vars]
spp4=mm4[,1:72]

# Hellinger transformation
spp_hell1=decostand(spp1, "clr", pseudocount=0.5)
spp_hell2=decostand(spp2, "clr", pseudocount=0.5)
spp_hell3=decostand(spp3, "clr", pseudocount=0.5)
spp_hell4=decostand(spp4, "clr", pseudocount=0.5)



# Transforming environmental data
envscho<-c("MO", "Ca", "Silt", "WHC", "Fe", "K", "Mg", "pH", "Cu", "Clay", "P", "Humidity", "N")
envst1=data.frame(scale(env1, scale=T, center=F)) %>% dplyr::rename(Silt=LIMO, Humidity=moisture, Clay=ARCILLA) %>% dplyr::select(all_of(envscho))
envst2=data.frame(scale(env2, scale=T, center=F))%>% dplyr::rename(Silt=LIMO, Humidity=moisture, Clay=ARCILLA) %>% dplyr::select(all_of(envscho))
envst3=data.frame(scale(env3, scale=T, center=F))%>% dplyr::rename(Silt=LIMO, Humidity=moisture, Clay=ARCILLA) %>% dplyr::select(all_of(envscho))
envst4=data.frame(scale(env4, scale=T, center=F))%>% dplyr::rename(Silt=LIMO, Humidity=moisture, Clay=ARCILLA) %>% dplyr::select(all_of(envscho))


#selecting using cca (no distance)
set.seed(126)
vares_cca1 <- cca(spp_hell1 ~., data=envst1)
envs1<-envfit(vares_cca1 ~ ., data=envst1)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("QIIME2"=".")

vares_cca2 <- cca(spp_hell2 ~., data=envst2)
envs2<-envfit(vares_cca2 ~ ., data=envst2)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Single Micop"=".")

vares_cca3 <- cca(spp_hell3 ~.,data=envst3)
envs3<-envfit(vares_cca3 ~ ., data=envst3)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Paired Micop"=".")

vares_cca4 <- cca(spp_hell4 ~.,data=envst4)
envs4<-envfit(vares_cca4 ~ ., data=envst4)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Kraken2"=".")

envs<- cbind(envs1, envs2, envs3, envs4)
rownames(envs)


```

- Data for plotting

```{r}
taxonomy_qiime2<- data.frame(read_qza("../Data/taxonomy_blast_dfc_0.98.qza")$data, check.names = F) %>% dplyr::select(Feature.ID,Taxon)
taxonomy_single_micop<- read.delim("../Data/table_micop_single.txt") %>% rownames_to_column(var = "Feature.ID") %>% dplyr::select(Feature.ID) %>% mutate(Taxon=Feature.ID)
taxonomy_paired_micop<- read.delim("../Data/table_micop_paired.txt") %>% rownames_to_column(var = "Feature.ID") %>% dplyr::select(Feature.ID) %>% mutate(Taxon=Feature.ID)
taxonomy_fungi<- read.delim("../Data/table_fungi_again.txt",
                            skip = 1, row.names = 1, check.names = F) %>% select_if(is.character) %>% rownames_to_column(
                              var = "#OTU ID") %>% dplyr::select(Feature.ID = "#OTU ID", Taxon= taxonomy)

map<- read.csv("../Data/coord.csv") %>% mutate_at(
  c(1,2,3,7), as.factor) %>% mutate(SampleID= paste0("P",pol, "S", Sitio,"T", Transecto ))

```

- Plot ccas envs
```{r, message=FALSE, warning=FALSE}

#png("cap_envs.png",width=6,height=4,units="in",res=1200)

library(viridis)
pal<- viridis(12, option = "H") 
pal2<- c( "#30123BFF","#30123BFF","#30123BFF","#4454C4FF","#4454C4FF","#4454C4FF",
                     "#4490FEFF","#4490FEFF","#4490FEFF" ,"#1FC8DEFF","#1FC8DEFF","#1FC8DEFF",
                     "#29EFA2FF","#29EFA2FF","#29EFA2FF", "#7DFF56FF","#7DFF56FF","#7DFF56FF",
                     "#C1F334FF","#C1F334FF","#C1F334FF", "#F1CA3AFF", "#F1CA3AFF", "#F1CA3AFF",
                     "#FE922AFF","#FE922AFF","#FE922AFF" , "#EA4F0DFF", "#EA4F0DFF", "#EA4F0DFF",
                     "#BE2102FF","#BE2102FF","#BE2102FF", "#7A0403FF","#7A0403FF","#7A0403FF")
                     #plots
par(mfrow=c(2,2),mar=c(2, 2, 1,1))

ordiplot(vares_cca1,type="n", main="QIIME2", cex.main=1)
text(cap.env1, dis="cn", scaling="sites", cex=0.6, col="red")
#points(cap.env1,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(vares_cca1, groups =meta1$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)
#text(x = vars_choosing1$CAP1,y = vars_choosing1$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing1$tax, font=3)
#text(cap.env1, dis="species", scaling="sites", cex=0.5, col="black")


ordiplot(vares_cca1,type="n", main="SINGLE MICOP", cex.main=1)
text(cap.env2, dis="cn", scaling="sites", cex=0.6, col="red")
#points(cap.env2,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(cap.env2, groups =meta2$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)
#text(x = vars_choosing2$CAP1,y = vars_choosing2$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing2$tax, font=3)

ordiplot(vares_cca1,type="n", main="PAIRED MICOP", cex.main=1)
text(cap.env3, dis="cn", scaling="sites", cex=0.6, col="red")
#points(cap.env3,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(cap.env3, groups =meta3$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)

#text(x = vars_choosing3$CAP1,y = vars_choosing3$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing3$tax, font=3)

```



- Vegetation analysis

```{r, warning=FALSE, message=FALSE}
#qiime2
mm1= veg %>% inner_join(table_qiime2_t %>%rownames_to_column(var = "SampleID"))
veg1=mm1[1:15] %>% column_to_rownames(var = "SampleID")
spp1=mm1[c(1,16:3153)]%>% column_to_rownames(var = "SampleID")

#single
mm2=veg%>% inner_join(table_single_t %>%rownames_to_column(var = "SampleID") )
veg2=mm2[1:15] %>% column_to_rownames(var = "SampleID")
spp2=mm2[c(1,16:225)]%>% column_to_rownames(var = "SampleID")

#paired
mm3=veg %>% inner_join(table_paired_t %>%rownames_to_column(var = "SampleID") )
veg3=mm3[1:15] %>% column_to_rownames(var = "SampleID")
spp3=mm3[c(1,16:249)]%>% column_to_rownames(var = "SampleID")

#kraken
mm4=veg %>% inner_join(table_kraken_t %>%rownames_to_column(var = "SampleID") )
veg4=mm2[1:15] %>% column_to_rownames(var = "SampleID")
spp4=mm4[c(1,16:87)]%>% column_to_rownames(var = "SampleID")
# Hellinger transformation

spp_hell1=decostand(spp1, "clr", pseudocount=0.5) 
spp_hell2=decostand(spp2, "clr", pseudocount=0.5)
spp_hell3=decostand(spp3, "clr", pseudocount=0.5)
spp_hell4=decostand(spp4, "clr", pseudocount=0.5)

# Compositional tranformation
#spp_hell1=decostand(otu.single(spp1), "clr", pseudocount=0.5) 
#spp_hell2=decostand(otu.single(spp2),  "clr", pseudocount=0.5)
#spp_hell3=decostand(otu.single(spp3),  "clr", pseudocount=0.5)
#spp_hell4=decostand(otu.single(spp4),  "clr", pseudocount=0.5)

# Transforming environmental data
vegt1=data.frame(scale(veg1, scale=T, center=F)) 
vegt2=data.frame(scale(veg2, scale=T, center=F))
vegt3=data.frame(scale(veg3, scale=T, center=F))
vegt4=data.frame(scale(veg4, scale=T, center=F))


#selecting using cca (no distance)
vares_cca1_veg <- cca(spp_hell1 ~., data=vegt1)
vegs1<-envfit(vares_cca1_veg ~., data=vegt1)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("QIIME2"=".")

vares_cca2_veg <- cca(spp_hell2 ~., data=vegt2)
vegs2<-envfit(vares_cca2_veg ~., data=vegt2)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Single Micop"=".")

vares_cca3_veg <- cca(spp_hell3 ~.,data=vegt3)
vegs3<-envfit(vares_cca3_veg ~., data=vegt3)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Paired Micop"=".")

vares_cca4_veg <- cca(spp_hell4 ~.,data=vegt4)
vegs4<-envfit(vares_cca4_veg ~., data=vegt4)$vectors[["pvals"]]%>% as.data.frame() %>% dplyr::select("Kraken2"=".")

vegs<- cbind(vegs1, vegs2, vegs3, vegs4)
rownames(vegs)

```
- Plot vegetaion ccas and caps 
```{r, warning=FALSE, message=FALSE}
#png("cap_veg.png",width=6,height=4,units="in",res=1200)
library(viridis)
par(mfrow=c(2,2),mar=c(2, 2, 1,1))
#png("cca_veg.png",width=6,height=4,units="in",res=1200)
par(mfrow=c(2,2),mar=c(2, 2, 1, 1))

ordiplot(vares_cca1_veg,type="n", main="QIIME2", cex.main=1)
text(vares_cca1_veg, dis="cn", scaling="sites", cex=0.6, col="red")
#points(vares_cca1_veg,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(vares_cca1_veg, groups =meta1$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)
#text(x = vars_choosing1$CAP1,y = vars_choosing1$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing1$tax, font=3)
#text(vares_cca1_veg, dis="species", scaling="sites", cex=0.5, col="black")


ordiplot(vares_cca2_veg,type="n",main="SINGLE MICOP", cex.main=1)
text(vares_cca2_veg, dis="cn", scaling="sites", cex=0.6, col="red")
#points(vares_cca2_veg,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(vares_cca2_veg, groups =meta2$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)
#text(x = vars_choosing2$CAP1,y = vars_choosing2$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing2$tax, font=3)

ordiplot(vares_cca3_veg,type="n",main="PAIRED MICOP", cex.main=1)
text(vares_cca3_veg, dis="cn", scaling="sites", cex=0.6, col="red")
#points(vares_cca3_veg,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(vares_cca3_veg, groups =meta3$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)

#text(x = vars_choosing3$CAP1,y = vars_choosing3$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing3$tax, font=3)

ordiplot(vares_cca4_veg,type="n",main="KRAKEN2", cex.main=1)
text(vares_cca4_veg, dis="cn", scaling="sites", cex=0.6, col="red")
#points(vares_cca4_veg,display="sites",cex=0.5,pc=19,  col = pal2)
ordiellipse(vares_cca4_veg, groups =meta4$Sites, col =pal, display = "sites",
            label=T, draw = "polygon", alpha = 50, label.cex=0.5, cex=0.7)
#text(x = vars_choosing4$CAP1,y = vars_choosing4$CAP2, 
#    cex=0.8, col="blue", labels=vars_choosing4$tax, font=3)



#dev.off()

```


