---
title: "Figures S4 and S5"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Figures S4 and S5 : vegetation and pca



```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(ggpubr)
library(rcartocolor)
veget<- read_excel("../Data/vegetacion.xlsx") %>% dplyr::select(
  -DAP, -CopaNS, -CopaEW,-volumenamdera, -distanciacopas, -diamcopa, -basal_area )

veget2<- veget %>% mutate(SampleID=case_when(
  SampleID=="P6S1T1" ~"P6S2T1",
  SampleID=="P6S1T2" ~"P6S2T2",
  SampleID=="P6S1T3" ~"P6S2T3",
  SampleID=="P6S2T1" ~"P6S1T1",
  SampleID=="P6S2T2" ~"P6S1T2",
  SampleID=="P6S2T3" ~"P6S1T3",
  TRUE~as.character(SampleID)))

metadata_secas<- read_excel("../Data/Metadatos.xlsx", sheet = "secas-marzo")
metadata<- read_excel("../Data/Metadatos.xlsx", sheet = "secas-marzo")


#declare data

veg<-veget2%>% separate(
  Especie, c("Genus", "Specie"), remove =F ) %>%   mutate(
    Genus=case_when(
      Genus=="Quecus"~ "Quercus",
      TRUE ~ as.character(Genus))) %>% mutate(
        Type=case_when(
          Genus=="Pinus"~ "Conifer",
          Genus=="Abies"~ "Conifer",
          Genus=="Juniperus"~ "Conifer",
          Genus=="Quercus"~ "Broadleaf",
          Genus=="Alnus"~ "Broadleaf",
          Genus=="Prunus"~ "Broadleaf",
          Genus=="Salix"~ "Broadleaf",
          Genus=="Arbutus"~ "Broadleaf") ) %>% mutate(
            Dominante=case_when(
              Genus=="Quercus"~ "Broadleaf",
              Genus=="Arbutus"~ "other Broadleaf",
              Genus=="Pinus"~ "Pinus",
              Genus=="Abies"~ "Abies",
              Genus=="Juniperus"~ "other Conifer",
              Genus=="Alnus"~ "other Broadleaf",
              Genus=="Alnus"~ "other Broadleaf",
              Genus=="Prunus"~ "other Broadleaf",
              Genus=="Salix"~ "other Broadleaf")  )

##proportions
prop_n<-veg %>% group_by(SampleID,Type) %>% dplyr::count()
prop_total<- veg %>% group_by(SampleID) %>% dplyr::count() %>% dplyr::rename(total=n)
prop<- prop_n %>% inner_join(prop_total)%>% mutate(
  prop=n/total*100)%>% dplyr::select(-n,-total) %>%  pivot_wider(
    . , names_from = "Type", values_from = "prop")  %>% mutate_if(
      is.numeric, ~round(.,digits = 2))  %>% mutate_if(
        is.numeric, ~replace(., is.na(.), 0)) %>% dplyr::rename(prop_Conif="Conifer",prop_Broadleaf="Broadleaf")

prop_n<-veg %>% group_by(SampleID,Genus) %>% dplyr::count()
prop_total<- veg %>% group_by(SampleID) %>% dplyr::count() %>% dplyr::rename(total=n)
prop_gen<- prop_n %>% inner_join(prop_total)%>% mutate(
  prop=n/total*100)%>% dplyr::select(-n,-total) %>%  pivot_wider(
    . , names_from = "Genus", values_from = "prop")  %>% mutate_if(
      is.numeric, ~round(.,digits = 2))  %>% mutate_if(
        is.numeric, ~replace(., is.na(.), 0))%>% 
  rename_with(~str_c("prop_", .), .cols = -SampleID)
data_prop <- prop %>% inner_join(prop_gen) %>% column_to_rownames(
  var = "SampleID") 



library(rcartocolor)
green_col= rcartocolor::carto_pal(n = 5, name = "Emrld")
brown_col = rcartocolor::carto_pal(n = 7, name = "BrwnYl")

plot_prop<-prop %>% pivot_longer(
  cols = -SampleID, names_to = "type", values_to = "prop") %>% inner_join(
    metadata  ) %>% ggbarplot(
      x = "Sites", y = "prop", fill="type", add = "mean")+
  theme_linedraw()+ylab("Proportion (%)")+
  xlab("Sites")+theme(legend.text = element_text(face = "plain"))+
  #  guides(fill = guide_legend(nrow = 30))+
  theme(legend.title = element_text(size = 9),
        #axis.ticks = element_blank(),
        legend.text = element_text(size = 9), 
        axis.text.x = element_text(size = 10),
        legend.key.size = unit(0.6, 'cm'), #change legend key size
        legend.key.height = unit(0.45, 'cm'), #change legend key height
        legend.key.width = unit(0.5, 'cm'),
        strip.text.x = element_text(size = 16),
        legend.box = "vertical")+ scale_fill_manual(name = "Type of \nvegetation",
                                                      labels = c("Broadleaf", "Conifers"),
                                                        values = c("#A65461","#074050"))

plot_prop_gen<-prop_gen %>% pivot_longer(
  cols = -SampleID, names_to = "type", values_to = "prop") %>% inner_join(
    metadata  ) %>% ggbarplot(
      x = "Sites", y = "prop", fill="type", add = "mean")+
  theme_linedraw()+ylab("Proportion (%)")+
  xlab("Sites")+theme(legend.text = element_text(face = "plain"))+
  #  guides(fill = guide_legend(nrow = 30))+
  theme(legend.title = element_text(size = 9),
        #axis.ticks = element_blank(),
        legend.text = element_text(size = 9), 
        axis.text.x = element_text(size = 10),
        legend.key.size = unit(0.6, 'cm'), #change legend key size
        legend.key.height = unit(0.45, 'cm'), #change legend key height
        legend.key.width = unit(0.5, 'cm'),
        strip.text.x = element_text(size = 16),
        legend.box = "vertical")+ scale_fill_manual(
          name = "Genera",
          labels = c("Abies", "Alnus", "Arbutus",
                     "Juniperus", "Pinus", "Prunus",
                     "Quercus", "Salix"),
          values = c ("#4C9B82", "#D39C83",  "#A65461" ,
                   "#82D091" , "#074050", "#541F3F", 
                    "#E0C2A2" , "#C1766F"))+theme(legend.text = element_text(face = "italic"))


library(cowplot)
all<-plot_grid(plot_prop+theme(
  axis.text.x = element_blank(), axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  plot.margin = unit(c(0.2, 0.2, 0, 0.2), "cm")),
  plot_prop_gen+ theme(plot.margin = unit(c(0, 0.2, 0.1, 0.2), "cm")), ncol = 1, labels = c("A)", "B)"), label_x = -0.01)
all

ggsave("veg_prop.png",width = 6, height = 6, dpi = 300, plot = all, device = "png")
```


```{r, warning=FALSE, message=FALSE}
#pca
envschose<-c( "K", "Ca", "Mg", "P",  "WHC","moisture" ,"Silt", "Fe", "pH", "Cu", "Clay", "N", "OM")


metadata_secas<- read_excel("../Data/Metadatos.xlsx", sheet = "secas-marzo")
fq_secas<- read_excel("../Data/fisicoq.xlsx", sheet = "seca")
fq_secas2<- read.csv("../Data/fisicoq-la.csv")

meta_fq_secas<- metadata_secas %>% full_join(fq_secas) #%>%  select(Sites:id_new,pH, MO, N, P) %>% mutate(Season="Dry")
meta_fq_secas_all<- metadata_secas %>% full_join(fq_secas) %>% full_join(fq_secas2, by = "SampleID")

env.16S=meta_fq_secas_all
df<- env.16S %>% dplyr::rename(Silt=LIMO, Clay=ARCILLA, Sand=ARENA, OM=MO) %>% dplyr::select(SampleID,envschose)
dfs=data.frame(df[1],scale(df[,2:14], center = T, scale = T)) %>% dplyr::select(
  SampleID,envschose) %>% 
  column_to_rownames(var = "SampleID")

#pca environmental

pca_env<- prcomp(dfs, center = F, scale. = F)
#biplot(pca_env)
metadatas_env<- as.data.frame(pca_env$x) %>% rownames_to_column(var = "SampleID") %>% 
  inner_join(metadata)
y<-ggordiplots::gg_ordiplot(pca_env, metadatas_env$Sites, hull = FALSE, 
                            spiders = TRUE,  ellipse = FALSE,   pt.size = 4,
                            plot =FALSE, label = FALSE)
z <- y$plot
a<-z+guides(
  color=guide_legend(title="Sites"))+theme_linedraw() +
  geom_vline(xintercept = 0, linetype = 2) +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2) +
  theme_linedraw()+
          scale_color_carto_d(name = "Sites", palette = "Safe") +
#  scale_color_viridis_d(option ="turbo" )+#color of points 
  theme(axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12), 
        legend.position = "right", 
        legend.box = "vertical",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  ggrepel::geom_label_repel(data=data.frame(pca_env$rotation) %>%   #arrows
                              rownames_to_column(var = "Feature.ID")%>%
                              slice(-6) %>% 
                              mutate(a=sqrt(PC1^2+PC2^2)) %>% 
                              mutate(PC1=PC1*10, PC2=PC2*10),
                            aes(x=PC1, y=PC2, label=Feature.ID ),
                            segment.colour = NA, col = 'black', 
                            fill= "white",
                            fontface="bold.italic", size=5) +theme(
                              legend.position = "right")  +
  guides(color = guide_legend(nrow =2 , title = "Sites"))+theme(
    legend.text = element_text(size = 12), legend.title = element_text(size = 14),
    axis.title = element_text(size = 16),
    plot.title = element_text(hjust = 1, size = 12))+
  guides(color = guide_legend(ncol = 1, title = "Sites"))+geom_label(
  data = y$df_mean.ord,
  aes(x = x, y = y, label=Group), 
  label.padding = unit(0.1, "lines"),label.size = 0.4,
  color="white", fill="black",fontface="bold",
)+
  geom_vline(xintercept = 0, linetype = 2, color="#88929b") +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2, color="#88929b")


a

ggsave("pca_env.png",width =8, height = 5, dpi = 300, plot = a, device = "png")


```
