---
title: "Figure 3. Heatmap"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Figure 3: Heatmap

- Load packages and data
```{r, warning=FALSE, message=FALSE}
library(vegan)
library(qiime2R)
library(readxl)
library(tidyverse)
library(ggh4x)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(rcartocolor)
source("../Code/general_functions.R")
metadata<-read_excel("../Data/Metadatos.xlsx") %>% mutate_if(is.numeric, as.factor)
meta<-metadata
table_single_micop<- read.delim("../Data/table_micop_single.txt") 
table_paired_micop<- read.delim("../Data/table_micop_paired.txt")
table_qiime2<- data.frame(
  read_qza("../Data/clustered_table_filter.qza")$data,
  check.names = F) %>% t() %>% as.data.frame(
  ) %>% rownames_to_column(
    var = "SampleID") %>% separate(
      SampleID, c(
        "id_metagenome", "R", "unmap", "Paired"), 
      sep = "_")%>% inner_join(
        meta) %>% dplyr::select(
          -id_metagenome:-Paired, -id_sequence:-id_fisicoq, -Sites, -Names) %>% column_to_rownames(
            var="SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)

table_fungi<- read.delim("../Data/table_kraken.txt", 
                         row.names = 1, check.names = F) %>% dplyr::select_if(
                           is.numeric)%>% t() %>% as.data.frame() %>% rownames_to_column(
                             var = "id_sequence") %>% separate(
                               ., "id_sequence", c(
                                 "kraken", "fungi", 
                                 "id_metagenome", "report", "bracken"), 
                               sep = "_") %>% dplyr::select(-kraken, -fungi, -report, -bracken) %>% full_join(
                                 metadata) %>% dplyr::select(-id_sequence:-Transecto, -id_metagenome, -Sites, -id_new, -Names, -id_fisicoq) %>% column_to_rownames(
                                   var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)


vector_order<- c("P1S1T1", "P1S1T2", "P1S1T3",
                 "P1S2T1", "P1S2T2", "P1S2T3",
                 "P2S1T1", "P2S1T2", "P2S1T3",
                 "P2S2T1", "P2S2T2", "P2S2T3",
                 "P3S1T1", "P3S1T2", "P3S1T3",
                 "P3S2T1", "P3S2T2", "P3S2T3",
                 "P4S1T1", "P4S1T2", "P4S1T3",
                 "P4S2T1", "P4S2T2", "P4S2T3",
                 "P5S1T1", "P5S1T2", "P5S1T3",
                 "P5S2T1", "P5S2T2", "P5S2T3",
                 "P6S1T1", "P6S1T2", "P6S1T3",
                 "P6S2T1", "P6S2T2", "P6S2T3")


vector_order<- c("P1S1",
                 "P1S2", 
                 "P2S1", 
                 "P2S2",
                 "P3S1", 
                 "P3S2", 
                 "P4S1", 
                 "P4S2", 
                 "P5S1", 
                 "P5S2", 
                 "P6S1", 
                 "P6S2")

#ordering

taxonomy_qiime2<- data.frame(read_qza("../Data/taxonomy_blast_dfc_0.98.qza")$data, check.names = F) %>% dplyr::select(Feature.ID,Taxon)
taxonomy_single_micop<- read.delim("../Data/table_micop_single.txt") %>% rownames_to_column(var = "Feature.ID") %>% dplyr::select(Feature.ID) %>% mutate(Taxon=Feature.ID)
taxonomy_paired_micop<- read.delim("../Data/table_micop_paired.txt") %>% rownames_to_column(var = "Feature.ID") %>% dplyr::select(Feature.ID) %>% mutate(Taxon=Feature.ID)
taxonomy_fungi<- read.delim("../Data/table_kraken.txt", 
                             row.names = 1, check.names = F) %>% select_if(is.character) %>% rownames_to_column(
                              var = "#OTU ID") %>% dplyr::select(Feature.ID = "#OTU ID", Taxon= taxonomy)

map<- read.csv("../Data/coord.csv") %>% mutate_at(
  c(1,2,3,7), as.factor) %>% mutate(SampleID= paste0("P",pol, "S", Sitio,"T", Transecto ))
metadata<-read_excel("../Data/Metadatos.xlsx") %>% mutate_if(is.numeric, as.factor)
```

- Formatting data for Heatmap
```{r, warning=FALSE, message=FALSE}
taxones_color<- read_csv("../Data/taxones_color.csv")

data_fun<- function(tab, taxonomy, metadata){
  table_genus<- tab %>%rownames_to_column(
    var = "Feature.ID") %>%  inner_join(taxonomy) %>% separate(
      Taxon, c("k","p","c","o","f","g","s"), sep = ";" ) %>% mutate_at(
        c("g"), ~str_replace(., "g__", ""))%>% 
    dplyr::mutate(g = stringr::str_trim(g, side = "both")) %>% mutate_if(
      is.character, ~replace_na(., "Unassigned")) %>% group_by(
        g) %>% summarise_if(is.numeric, sum) %>% column_to_rownames(
          var = "g") %>%  mutate(
            all= rowSums(.)) %>% dplyr::arrange(
              -all) %>% rel_ab(.) %>%as.data.frame( ) %>%  rownames_to_column(
              var = "Taxon")%>% filter(!Taxon=="unidentified" ,
                                       !Taxon=="Unassigned") #%>%slice(
                                         #c(1:50))  %>% pivot_longer(
                                         #  ., cols = -Taxon, 
                                          # names_to ="SampleID", 
                                           #values_to = "relab" ) %>% filter( !SampleID=="all")

#cols<- table_genus %>% inner_join(taxones_color) %>% arrange(Taxon)
#col <- as.character(cols$color)
#names(col) <- as.character(cols$Taxon)
  
#barplot_genus<- table_genus %>% inner_join(metadata)%>% dplyr::select(
 #   Taxon, SampleID, relab) %>% pivot_wider(
  #    names_from = Taxon, values_from = relab) %>% column_to_rownames(
   #     var = "SampleID") %>% t() %>% as.data.frame()
  }

data_fun2<- function(tab, taxonomy, metadata){
  table_genus<- tab %>%rownames_to_column(
  var = "Feature.ID") %>%  inner_join(taxonomy) %>% separate(
    Taxon, c("k","p","c","o","f","g","s"), sep = "__" ) %>% mutate_at(
      c("g"), ~str_replace(., "g__", "")) %>% mutate_at(
        c("g"), ~str_replace(., "g__", "")) %>% mutate_if(
          is.character, ~replace_na(., "Unassigned")) %>% group_by(
            g) %>% summarise_if(is.numeric, sum) %>% column_to_rownames(
              var = "g") %>%  mutate(
                all= rowSums(.)) %>% dplyr::arrange(-all) %>% rel_ab(.) %>% as.data.frame() %>% rownames_to_column(
                  var = "Taxon")%>% filter(!Taxon=="unidentified" , !Taxon=="Unassigned") #%>% slice(
                    #c(1:50))  %>% pivot_longer(
                     # ., cols = -Taxon, names_to ="SampleID", 
                      #values_to = "relab" ) %>% filter(!SampleID=="all")

#cols<- table_genus %>% inner_join(taxones_color) %>% arrange(Taxon)
#col <- as.character(cols$color)
#names(col) <- as.character(cols$Taxon)


#barplot_genus<- table_genus %>% inner_join(metadata)%>% dplyr::select(
 # Taxon, SampleID, relab) %>% pivot_wider(
  #  names_from = Taxon, values_from = relab) %>% column_to_rownames(
   #   var = "SampleID") %>% t() %>% as.data.frame()
  }



data_qiime2<- data_fun(table_qiime2, taxonomy_qiime2, metadata) %>%
  column_to_rownames(var = "Taxon")
data_qiime22= data_qiime2 %>% dplyr::select(-all) %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "SampleID") %>% full_join(metadata) %>% group_by(Poligono, Sitio) %>% summarize_if(
    is.numeric, mean  ) %>% mutate(SampleID=paste0("P", Poligono,"S", Sitio))%>% column_to_rownames(var = "SampleID") %>% 
  dplyr::select_if(is.numeric) %>% t() %>% as.data.frame()
data_qiime2_order=data_qiime22[, match(vector_order, colnames(data_qiime22))] %>% 
  rename_if(is.numeric, ~paste0(.,"_qiime2"))%>% rownames_to_column(var="gen")


data_fungi<- data_fun(table_fungi, taxonomy_fungi, metadata) %>%
  column_to_rownames(var = "Taxon")
data_fungi2= data_fungi %>% dplyr::select(-all) %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "SampleID") %>% full_join(metadata) %>% group_by(Poligono, Sitio) %>% summarize_if(
    is.numeric, mean  ) %>% mutate(SampleID=paste0("P", Poligono,"S", Sitio))%>% column_to_rownames(var = "SampleID") %>% 
  dplyr::select_if(is.numeric) %>% t() %>% as.data.frame()

data_fungi_order=data_fungi2[, match(vector_order, colnames(data_fungi2))]%>%
  rename_if(is.numeric, ~paste0(.,"_kraken2")) %>% rownames_to_column(var="gen")

data_single<- data_fun2(table_single_micop, taxonomy_single_micop, metadata) %>%
  column_to_rownames(var = "Taxon")
data_single2= data_single %>% dplyr::select(-all) %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "SampleID") %>% full_join(metadata) %>% group_by(Poligono, Sitio) %>% summarize_if(
    is.numeric, mean  ) %>% mutate(SampleID=paste0("P", Poligono,"S", Sitio))%>% column_to_rownames(var = "SampleID") %>% 
  dplyr::select_if(is.numeric) %>% t() %>% as.data.frame()
data_single_order=data_single2[, match(vector_order, colnames(data_single2))]%>%
  rename_if(is.numeric, ~paste0(.,"_single"))%>% rownames_to_column(var="gen")

data_paired<- data_fun2(table_paired_micop, taxonomy_paired_micop, metadata) %>%
  column_to_rownames(var = "Taxon")
data_paired2= data_paired %>% dplyr::select(-all) %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "SampleID") %>% full_join(metadata) %>% group_by(Poligono, Sitio) %>% summarize_if(
    is.numeric, mean  ) %>% mutate(SampleID=paste0("P", Poligono,"S", Sitio))%>% column_to_rownames(var = "SampleID") %>% 
  dplyr::select_if(is.numeric) %>% t() %>% as.data.frame()

data_paired_order=data_paired2[, match(vector_order, colnames(data_paired2))]%>%
  rename_if(is.numeric, ~paste0(.,"_paired"))%>% rownames_to_column(var="gen")




merge_data<- data_qiime2_order %>% full_join(
  data_single_order)%>% full_join(
    data_paired_order)%>% full_join(
      data_fungi_order) %>% replace(is.na(.), 0)  %>% mutate(gen=case_when(
        gen=="Leptosphaeria maculans species complex" ~ "Leptosphaeria", 
        TRUE ~ as.character(gen)))%>% column_to_rownames(
        var = "gen") %>% mutate(proms=rowMeans(.)) %>% dplyr::arrange(-proms) %>% slice(
          1:60)%>% dplyr::select(-proms) %>% mutate_all(., funs(R = case_when(
          . <= 0.001 ~ 0,
          . >  0.001 & .  <= 0.005 ~ 1,
          . >  0.005 & .  <= 0.01 ~ 2,
          . >  0.01 & .  <= 0.10 ~ 3,
          . >  0.10 & .  <= 0.20 ~ 4,
          . >  0.20 & .  <= 1.00 ~ 5,
          . >  1.00 & .  <= 2.00 ~ 6,
          . >  2.00 & .  <= 5.00 ~ 7,
          . >  5.00 & .  <= 10.00 ~ 8,
          . >  10.00 & .  <= 25.00 ~ 9,
          . >  25.00 & .  <= 50.00 ~ 10,
          . >  50.00 & .  <= 75.00 ~ 11,
          . >  75.00 ~ 12))) %>%select_at(
            vars(contains("_R"))) %>% select_all(~str_replace(., "_R", ""))
```

- Setting annotations and format for Heatmap
```{r, warning=FALSE, message=FALSE}
col_fun2 = colorRamp2(c(0,  1, 1+1e-5,10,50, 100), 
                      viridis(6, option = "F", direction = -1))
#my_palette <- viridis::viridis(n = 12, option = "F", direction = -1)
col_fun = colorRamp2(c(0,  1, 1+1e-5,5,5+1e-5,10,10+1e-5,50,50+1e-5, 75, 75+1e-5,100), 
                      viridis(12, option = "F", direction = -1))
my_palette <- carto_pal(8, "SunsetDark")

#annotation ids
annotation_columns<- data.frame(id=colnames(merge_data)) 
rownames(annotation_columns) <- colnames(heatmap)

#set.seed(123)
split = rep(1:4, each = 12)

Sites<- c(1,1,1,
          2,2,2,
          3,3,3,
          4,4,4,
          5,5,5,
          6,6,6,
          7,7,7,
          8,8,8,
          9,9,9,
          10,10,10,
          11,11,11,
          12,12,12)

Sites = 1:12

ha = HeatmapAnnotation("Method" = anno_block(gp = gpar(
  fill = c("black" ,"black" ,"black", "black")), 
  labels = c("GENEIOUS+UNITE", "SINGLE MICOP", "PAIRED MICOP", "KRAKEN2"), 
  labels_gp = gpar(col = "white", fontsize = 7, fontface= "bold")))

y_colors = carto_pal(12, "Safe")


cols_ho<- list("Sites" = c("1"="#88CCEE","2"="#CC6677" ,
                           "3"= "#DDCC77" , "4"="#117733", 
                           "5"= "#332288","6"= "#AA4499",
                           "7"="#44AA99","8"="#999933",
                           "9"= "#882255" ,"10"="#661100",
                           "11"= "#6699CC","12"= "#888888"))


ho = HeatmapAnnotation("Sites" = c(rep(Sites, 4)),
                       which = "col", col = cols_ho,
                       annotation_name_gp = gpar(fontsize=8,
                                                 fontface="bold"),
                       show_legend = F, gp = gpar(
                         col = "white", fontize=12), 
                       simple_anno_size = unit(0.25, "cm"),
                       show_annotation_name = T)


tex = HeatmapAnnotation(
  text = anno_text(rep(c(1:12), 4),
    rot = 0,  
   location = 0.6,
   just = "center",
    gp = gpar(fontsize = 6)))
  


#annotatio row (filas)
#para hccer....cambiar el guidls_all.tsv con la nueva data
guilds<- read_tsv("../Data/guilds_all.txt") %>% group_by(Taxon, Guild, `Trophic Mode`) %>% 
  mutate(Guilds=case_when(
    Guild=="Dung Saprotroph-Undefined Saprotroph-Wood Saprotroph"~"Dung Sap.-Undef Sap.-Wood Sap.",
        Guild=="Ectomycorrhizal-Fungal Parasite"~"Ectomycorrhizal-Fung.Parasit",
    Guild=="Animal Pathogen-Endophyte-Endosymbiont-Epiphyte-Soil Saprotroph-Undefined Saprotroph"~"Animal P-Endoph/symb-Undef. Sap.",
    Guild=="Endophyte-Plant Pathogen-Wood Saprotroph"~"Endophyte-Pathogen-Saprotroph",
    Guild=="Animal Pathogen-Endophyte-Epiphyte-Fungal Parasite-Plant Pathogen-Wood Saprotroph"~"Animal-Plant P-Endophyte-Saprotroph",
    Guild=="Animal
Pathogen-Endophyte-Epiphyte-Undefined Saprotroph" ~"Animal-Plant P-Endophyte-Saprotroph",
Guild=="Animal Pathogen-Endophyte-Epiphyte-Undefined Saprotroph"~"Animal-Plant P-Endophyte-Saprotroph",
    Guild=="Animal Pathogen-Endophyte-Plant Pathogen-Undefined Saprotroph"~"Animal-Plant P-Endophyte-Saprotroph",
    Guild=="Endophyte-Litter Saprotroph-Soil Saprotroph-Undefined Saprotroph"~"Endophyte-Undefined Saprotrop",
    Guild=="Animal Endosymbiont-Animal Pathogen-Plant Pathogen-Undefined Saprotroph"~"Animal-Plant endosymb-P-Undef. Sap.",
Guild=="Endophyte-Plant Pathogen-Undefined Saprotroph"~"Endophyte-Plant Pathogen-Undef. Sap.",
Guild=="Ectomycorrhizal-Undefined Saprotroph"~"Ectomycorrhizal-Undef. Sap.",
Guild=="Animal Pathogen-Fungal Parasite-Undefined Saprotroph"~"Animal P-Fungal Parasite-Undef. Sap.",
    Guild=="Fungal Parasite-Plant Pathogen-Plant Saprotroph"~"Fungal Parasite-Plant Path-Plant Sap.",
Guild=="Animal Pathogen-Endophyte-Plant Pathogen-Soil Saprotroph-Wood Saprotroph" ~"Animal Pathogen-Endoph-Plant P-Soil/Wood Sap", 
Guild=="Ectomycorrhizal-Orchid Mycorrhizal-Root Associated Biotroph" ~"Ectomycorrhizal-Mycorrhizal-Biotroph",
Guild=="Clavicipitaceous Endophyte-Plant Pathogen" ~"Clavicipitaceous Endophyte-Plant Pat.",
Guild=="Dung Saprotroph-Endophyte-Epiphyte-Wood Saprotroph" ~"Dung Sap.-Endo.-Epiph.-Wood Sap.",
    TRUE~as.character(Guild)))# %>% filter(relab>1)
#Dung Saprotroph-Endophyte-Epiphyte-Wood Saprotroph
#%>% #mutate(Guilds=case_when(
  #Guild=="Dung Saprotroph-Undefined Saprotroph-Wood Saprotroph" ~ "Undefined Saprotroph", 
#  TRUE ~ as.character(Guild)))
annotation_rows<- merge_data %>% rownames_to_column(
  var = "Taxon") %>% left_join(
  guilds) %>%dplyr::select(-OTUID,-taxonomy) %>%  distinct()%>%dplyr::select_if(
is.character) %>% replace(
  is.na(.), "Unassigned") %>% distinct() %>% slice(-5) %>% column_to_rownames(
    var = "Taxon") %>% dplyr::rename(Trophic=`Trophic Mode`)

library(rcartocolor)

animal_path=carto_pal(n = 8, name = "SunsetDark" )
plant_path=carto_pal(n = 8, name = "Peach")
mico_path=carto_pal(n = 8, name = "TealGrn")
endo_path=carto_pal(n = 8, name = "Teal")
brown= carto_pal(n = 8, name = "BrwnYl")



cols_guild <- list('Guild' = c(
"Unassigned"= "#85929e",
  #"Animal Pathogen-Endophyte-Plant Pathogen-Soil Saprotroph-Wood Saprotroph" = "#FCDE9C",
  "Animal Pathogen-Endoph-Plant P-Soil/Wood Sap" = "#FAAC7B",
  "Animal Pathogen-Endophyte-Epiphyte-Fungal Parasite-Plant Pathogen-Wood Saprotroph" = "#F28170",
  "Animal Pathogen-Soil Saprotroph" = "#E85E6E",
  "Animal Endosymbiont-Animal Pathogen-Plant Pathogen-Undefined Saprotroph" = "#E04572",
  "Animal Pathogen" = "#D23377",
  "Animal Pathogen-Endophyte-Endosymbiont-Epiphyte-Soil Saprotroph-Undefined Saprotroph" = "#B02378",
  "Animal P-Endoph/symb-Undef. Sap." = "#7C1D6F",
  "Animal Pathogen-Undefined Saprotroph" = "#FCDE9C" ,


"Plant Pathogen" = "#FDE0C5",
  "Fungal Parasite" = "#FACEAA",
  "Animal-Plant P-Endophyte-Saprotroph" = "#F8BB92",
  "Animal-Plant endosymb-P-Undef. Sap." = "#F6A77C",
  "Animal Pathogen-Fungal Parasite-Undefined Saprotroph" = "#F39369",
  "Animal P-Fungal Parasite-Undef. Sap." = "#F17D58",
  "Fungal Parasite-Plant Pathogen-Plant Saprotroph" = "#EE654A",
  "Fungal Parasite-Plant Path-Plant Sap." = "#EB4A40",
  "Plant Pathogen-Undefined Saprotroph" = "#EB4A40" ,


"Ectomycorrhizal-Orchid Mycorrhizal-Root Associated Biotroph"="#b4ff68",
"Ectomycorrhizal-Mycorrhizal-Biotroph"="#b4ff68",
"Ectomycorrhizal" = "#7FC97F",
"Ectomycorrhizal-Fungal Parasite"="#58d68d",
"Ectomycorrhizal-Undefined Saprotroph"="#edf2a3",
"Ectomycorrhizal-Undef. Sap."="#edf2a3",
"Ericoid Mycorrhizal"="#a2ab16",
"Arbuscular Mycorrhizal"="#008000",


#"Ectomycorrhizal-Orchid"="#0000FF", #no sale

"Ectomycorrhizal-Orchid Mycorrhizal-Root Associated Biotroph" = "#B0F2BC",    
  "Ectomycorrhizal-Mycorrhizal-Biotroph" = "#8EE9AE",                        
  "Ectomycorrhizal" = "#70DEA7",                                              
  "Ectomycorrhizal-Fungal Parasite" = "#57D0A3",                              
  "Ectomycorrhizal-Undefined Saprotroph" = "#43BEA3",                         
  "Ectomycorrhizal-Undef. Sap." = "#34AAA2",                                  
  "Ericoid Mycorrhizal" = "#2A949E",                                          
  "Arbuscular Mycorrhizal" = "#257D98",


#"Epiphyte"="#02f0a5",
#"Lichenized"="#DAF7A6",



  "Endophyte" = "#D1EEEA",                                    
  "Endophyte-Plant Pathogen" = "#ADDDDB",                      
  "Endophyte-Plant Pathogen-Undefined Saprotroph" = "#8FCACD", 
  "Endophyte-Plant Pathogen-Undef. Sap." = "#74B5BF",         
  "Endophyte-Pathogen-Saprotroph" = "#5D9FB0",                
  "Endophyte-Plant Pathogen-Wood Saprotroph" = "#49879F",     
  "Endophyte-Litter Saprotroph-Soil Saprotroph-Undefined Saprotroph" = "#386E8B", 
  "Endophyte-Undefined Saprotrop" = "#2A5674",   
"Clavicipitaceous Endophyte-Plant Pat."="#8FCACD",


"Dung Saprotroph" = "#EDE5CF",                      
  "Soil Saprotroph" = "#E1C7A8",                      
  "Undefined Saprotroph" = "#D6A68B",                 
  "Wood Saprotroph" = "#C88677",                      
  "Plant Pathogen-Wood Saprotroph" = "#B56769",      
  "Dung Saprotroph-Wood Saprotroph" = "#9B4B5D",      
  "Dung Sap.-Endo.-Epiph.-Wood Sap." = "#7A3350",     
  "Dung Sap.-Undef Sap.-Wood Sap." = "#541F3F"  
 # "Dung Saprotroph-Undefined Saprotroph-Wood Saprotroph" = "#EDE5CF" # Color 1 


))


cols_tro <- list('Trophic' = c(
"Pathotroph"=	"#EE654A",
"Pathotroph-Saprotroph"=	"#541F3F",
"Pathotroph-Symbiotroph"="#EB4A40",
"Saprotroph"=	"#C88677",
"Saprotroph-Symbiotroph"=	"#EDE5CF",
"Symbiotroph"=	"#008000",
"Unassigned"= "#85929e",
"Pathotroph-Saprotroph-Symbiotroph"=	"#E04572"))

annguild = HeatmapAnnotation("Guild" = annotation_rows$Guilds, 
                            which = "row", col = cols_guild,
                            show_legend = T,   
                            show_annotation_name = T,
                            annotation_name_gp =gpar(
                              fontsize = 7, fontface="bold"),
                            annotation_legend_param = list(
                              title_gp = gpar(fontsize = 7, 
                                              fontface="bold"),
                              labels_gp = gpar(fontsize = 7),
                             direction ="horizontal",
                            grid_width = unit(0.3, "cm"),
                             grid_height = unit(0.1, "cm")),
                            
                            simple_anno_size = unit(0.3, "cm"),
                            gp = gpar(col = "white"))

anntro = HeatmapAnnotation("Trophic" = annotation_rows$Trophic, 
                             which = "row", col = cols_tro,
                             show_legend = T,   
                           show_annotation_name = T,
                             annotation_name_gp =gpar(
                               fontsize = 7,  fontface="bold"),
                             annotation_legend_param = list(
                               title_gp = gpar(fontsize = 7, 
                                               fontface="bold"),
                               labels_gp = gpar(fontsize =7),
                                  direction ="horizontal",
                               grid_width = unit(0.3, "cm"),
                           grid_height = unit(0.1, "cm")),
                           simple_anno_size = unit(0.3, "cm"),
                           gp = gpar(col = "white"))

#annotation_rows[is.na(annotation_rows)] <- "Unassigned"


```

- Ploting heatmap
```{r, warning=FALSE, message=FALSE, fig.height=7, fig.width=11}
my_palette <- carto_pal(8, "ag_Sunset")
my_palette <- rev(my_palette)


heats<-ComplexHeatmap::Heatmap(
  merge_data,
  col = my_palette,
   row_dend_width = unit(0.4, "cm"),
  width = ncol(merge_data)*unit(2, "mm"), 
    height = nrow(merge_data)*unit(2.4, "mm"),
  heatmap_legend_param = list(direction = "horizontal",
                          title = "Relative abund(%)",
                             grid_height = unit(0.2, "cm"),
                              legend_height = unit(1, "cm"),
                              labels_gp = gpar(fontsize = 7),
                              title_gp = gpar(fontsize = 6, 
                                              fontface="bold"),
                              at = c(0,1, 10,  50, 100), break_dist = 1),
  rect_gp = gpar(col = "white"), 
  cluster_columns = F, cluster_rows = T,show_row_dend = FALSE,
  show_heatmap_legend = TRUE, top_annotation = c(ha,ho),
  right_annotation = c(anntro, annguild),
  column_order = sort(colnames(merge_data)),
  column_split = split, column_title = NULL,
show_column_names = T,
row_names_gp = gpar(fontsize=7.5, fontface="italic"),
column_names_rot=90,
column_labels = gt_render(rep(1:12, 4)),
column_names_gp = gpar(fontsize = 6),
column_title_gp = gpar(
  fill = c("#800000" ,"#808000" ,"#008000", "#D35400", "#2E4053" )))



lgd1 = Legend(at = 1:12, title = "Sites", nrow = 1,
              title_position = "leftcenter",
              legend_gp = gpar(fill = rcartocolor::carto_pal(n = 12, name = "Safe")),
  labels_gp = gpar(fontsize = 8),
  title_gp = gpar(fontsize = 9, fontface="bold"))


lgd2 = Legend(at = sort(unique(annotation_rows$Guild)), 
              legend_gp = gpar(fill = cols_guild$Guild), 
              title = "Guild",  ncol = 2, gap = unit(0.1, "cm"),
              labels_gp = gpar(fontsize = 7),
              title_gp = gpar(fontsize = 7, fontface="bold"))
lgd3 = Legend(at = sort(unique(annotation_rows$Trophic)), 
              legend_gp = gpar(fill = cols_tro$Trophic),
              title = "Trophic", ncol = 1,gap = unit(1, "cm"),
              labels_gp = gpar(fontsize =7),
              title_gp = gpar(fontsize = 7, fontface="bold"))


#draw(heats, heatmap_legend_side = "right",
     #annotation_legend_side = "top", 
     #merge_legend=F,
     #annotation_legend_list = list(lgd1))


heatm<-grid.grabExpr(draw(heats, heatmap_legend_side = "right",
                          annotation_legend_side = "top", 
                          merge_legend=F,
                         annotation_legend_list = list(lgd1)))
                     
heats
ggsave('Figure3.pdf', width = 8, height = 7, dpi = 600, plot =heatm, device = "pdf")

```

### Summaricing data

```{r}

mean_data<- data_qiime2_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowMeans(.)) %>% dplyr::select(qiime2=all) %>% rownames_to_column(var = "gen") %>% full_join(
  data_single_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowMeans(.)) %>% dplyr::select(single=all) %>% rownames_to_column(var = "gen"))%>% full_join(
    data_paired_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowMeans(.)) %>% dplyr::select(paired=all) %>% rownames_to_column(var = "gen"))%>% full_join(
      data_fungi_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowMeans(.)) %>% dplyr::select(kraken=all) %>% rownames_to_column(var = "gen")) %>% replace(is.na(.), 0)  %>% mutate(gen=case_when(
        gen=="Leptosphaeria maculans species complex" ~ "Leptosphaeria", 
        TRUE ~ as.character(gen)))%>% column_to_rownames(
        var = "gen") %>% mutate(proms=rowMeans(.)) %>% dplyr::arrange(-proms) %>% 
  mutate_if(is.numeric, ~round(., digits = 2))

library(matrixStats)

sd_data<- data_qiime2_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowSds(as.matrix(.))) %>% dplyr::select(qiime2=all) %>% rownames_to_column(var = "gen") %>% full_join(
  data_single_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowSds(as.matrix(.))) %>% dplyr::select(single=all) %>% rownames_to_column(var = "gen"))%>% full_join(
    data_paired_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowSds(as.matrix(.))) %>% dplyr::select(paired=all) %>% rownames_to_column(var = "gen"))%>% full_join(
      data_fungi_order%>% column_to_rownames(var = "gen") %>% mutate(all=rowSds(as.matrix(.))) %>% dplyr::select(kraken=all) %>% rownames_to_column(var = "gen")) %>% replace(is.na(.), 0)  %>% mutate(gen=case_when(
        gen=="Leptosphaeria maculans species complex" ~ "Leptosphaeria", 
        TRUE ~ as.character(gen)))%>% column_to_rownames(
        var = "gen") %>% mutate(proms=rowSds(as.matrix(.))) %>%
                                  dplyr::arrange(-proms)%>% 
  mutate_if(is.numeric, ~round(., digits = 2))

```


```{r}
library(QsRutils)

tabla1=goods(t(table_qiime2))
tabla2=goods(t(table_single_micop))
tabla3=goods(t(table_paired_micop))
tabla4=goods(t(table_fungi))

mean(tabla1$goods)
mean(tabla2$goods)
mean(tabla3$goods)
mean(tabla4$goods)

```

