---
title: "Figure S7"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

## Figure S7: corrplot

- Loading libraries 
```{r, warning=FALSE, message=FALSE}
library(reshape2)
library(tidyverse)
library(picante)
library(Rmisc)
library(readxl)
source("../Code/functions_beta.R")
```

- loading environmental data, and correlation

```{r, warning=FALSE, message=FALSE}
metadata_secas<- read_excel("../Data/Metadatos.xlsx", sheet = "secas-marzo")
fq_secas<- read_excel("../Data/fisicoq.xlsx", sheet = "seca")
fq_secas2<- read.csv("../Data/fisicoq-la.csv")
meta_fq_secas<- metadata_secas %>% full_join(fq_secas) 
meta_fq_secas_all<- metadata_secas %>% full_join(
  fq_secas) %>% full_join(fq_secas2, by = "SampleID")

env=meta_fq_secas_all
#standardize environmental data
df<- env%>% dplyr::select(
  SampleID, pH:Mn, moisture, WHC:CONDUC, ARCILLA:ARENA) %>% column_to_rownames(var = "SampleID")
#df<-df[-1]
df<- df %>% dplyr::select(-CONDUC, -ARENA, -Mn) #selectig r<0.7
dfs=data.frame(scale(df[,1:13], center = T, scale = T)) 
#dfs$Sites<-NA
#dfs$Sites<- df$Sites

# checking collinearity
#cotable<-cor.table(na.omit(dfs[,1:7]))$r
cors<- dfs %>% dplyr::rename(Humidity=moisture, Silt=LIMO,OM=MO,
                             Clay=ARCILLA) %>% dplyr::select(-Humidity)
corss<- cor(cors, method = "pearson")


```

- loading and formatting vegetation data and correlation
```{r, warning=FALSE, message=FALSE}
map<- read.csv("../Data/coord.csv") %>% mutate_at(
  c(1,2,3,7), as.factor) %>% mutate(SampleID= paste0("P",pol, "S", Sitio,"T", Transecto ))
metadata<-read_excel("../Data/Metadatos.xlsx") %>% mutate_if(is.numeric, as.factor)

veget<- read_excel("../Data/vegetacion.xlsx") %>% dplyr::select(
  -DAP, -CopaNS, -CopaEW,-volumenamdera, -distanciacopas, -diamcopa, -basal_area )

#declare data

veg<-veget %>% separate(
  Especie, c("Genus", "Specie"), remove =F ) %>%   mutate(
    Genus=case_when(
      Genus=="Quecus"~ "Quercus",
      TRUE ~ as.character(Genus))) %>% mutate(
        Type=case_when(
          Genus=="Pinus"~ "Conifer",
          Genus=="Abies"~ "Conifer",
          Genus=="Juniperus"~ "Conifer",
          Genus=="Quercus"~ "Broadleaf",
          Genus=="Alnus"~ "Broadleaf",
          Genus=="Prunus"~ "Broadleaf",
          Genus=="Salix"~ "Broadleaf",
          Genus=="Arbutus"~ "Broadleaf") ) %>% mutate(
            Dominante=case_when(
              Genus=="Quercus"~ "Broadleaf",
              Genus=="Arbutus"~ "other Broadleaf",
              Genus=="Pinus"~ "Pinus",
              Genus=="Abies"~ "Abies",
              Genus=="Juniperus"~ "other Conifer",
              Genus=="Alnus"~ "other Broadleaf",
              Genus=="Alnus"~ "other Broadleaf",
              Genus=="Prunus"~ "other Broadleaf",
              Genus=="Salix"~ "other Broadleaf")  )

##proportions
prop_n<-veg %>% group_by(SampleID,Type) %>% dplyr::count()
prop_total<- veg %>% group_by(SampleID) %>% dplyr::count() %>% dplyr::rename(total=n)
prop<- prop_n %>% inner_join(prop_total)%>% mutate(
prop=n/total*100)%>% dplyr::select(-n,-total) %>%  pivot_wider(
    . , names_from = "Type", values_from = "prop")  %>% mutate_if(
      is.numeric, ~round(.,digits = 2))  %>% mutate_if(
      is.numeric, ~replace(., is.na(.), 0)) %>% dplyr::rename(prop_Conif="Conifer",prop_Broadleaf="Broadleaf")

prop_n<-veg %>% group_by(SampleID,Genus) %>% dplyr::count()
prop_total<- veg %>% group_by(SampleID) %>% dplyr::count() %>% dplyr::rename(total=n)
prop_gen<- prop_n %>% inner_join(prop_total)%>% mutate(
  prop=n/total*100)%>% dplyr::select(-n,-total) %>%  pivot_wider(
    . , names_from = "Genus", values_from = "prop")  %>% mutate_if(
      is.numeric, ~round(.,digits = 2))  %>% mutate_if(
      is.numeric, ~replace(., is.na(.), 0))%>% 
  rename_with(~str_c("prop_", .), .cols = -SampleID)

# mean data
means<-veg %>% group_by(SampleID) %>% summarise_if(is.numeric, ~mean(., na.rm = TRUE))%>% 
  rename_with(~str_c("total_mean_", .), .cols = -SampleID)
veg_group<- veg %>% group_by(SampleID,Genus)%>% summarise_if(  is.numeric, ~mean(., na.rm = TRUE)) %>% dplyr::select(-Sites) #%>% column_to_rownames(var = "SampleID")

means_genus<-function(y){veg_group %>% dplyr::select(
  SampleID, Genus,y) %>%  pivot_wider(
  . , names_from = "Genus", values_from = y)  %>% mutate_if(
    is.numeric, ~round(.,digits = 2))  %>% mutate_if(
      is.numeric, ~replace(., is.na(.), 0))%>% 
    rename_with(~str_c(paste0("mean_",y, "_"), .), .cols = -SampleID)}

vect<-c( "Height",   "coverage"    )
mean.list.genus <- vector("list")


for(i in vect) {
  mean.list.genus [[i]] <- means_genus(y = i)
}

mean.df.genus<-   mean.list.genus [[1]] %>% inner_join(
  mean.list.genus [[2]])

data_prop <- prop %>% inner_join(prop_gen) %>% column_to_rownames(
  var = "SampleID") 

data_veg_mean<- means %>% inner_join(mean.df.genus) %>% dplyr::select_at(
  vars(-contains("sites"))) %>%   dplyr::select_at(vars(-contains("volumen")))%>% column_to_rownames(
    var = "SampleID")

data_propt<- data_prop %>% log_norm() #%>% as.matrix() %>%scale(scale = T, center = T) 

vegeta= merge(data_propt, data_veg_mean, by=0)%>%dplyr::rename(
  SampleID="Row.names") %>% column_to_rownames(
    var = "SampleID")  %>% as.matrix() %>%scale(
      scale = T, center = T) %>% as.data.frame() %>% rownames_to_column(
        var = "SampleID") %>% dplyr::select(
          -prop_Conif, -prop_Quercus,
          -mean_Height_Abies, -mean_Height_Arbutus,
          -mean_Height_Juniperus,-mean_Height_Pinus,
          -mean_Height_Quercus,-mean_Height_Prunus,
          -mean_Height_Alnus, -mean_Height_Salix,
          -mean_coverage_Prunus,  -mean_coverage_Salix,
          -mean_coverage_Alnus, -mean_coverage_Abies  )

cor2<- vegeta[-1]
cor2<- cor2 %>% as.data.frame( ) %>% 
   select_all(~str_replace(., "prop_", ""))  %>% 
   select_all(~str_replace(., "mean_", "")) %>% 
   select_all(~str_replace(., "coverage_", "cov_")) 
   
corss2<- cor(cor2, method = "pearson") 

#write_tsv(vegeta,"../Data/vegeta.tsv")
```

- Plot pca vegetation

```{r, warning=FALSE, message=FALSE}
#pca vegeta
vegeta_col<- c("SampleID", "Broadleaf", "Abies", "Pinus", "Salix", "Arbutus",
               "Alnus", "Juniperus", "Prunus", "total_Height", "total_coverage",
               "cov_Pinus", "cov_Arbutus", "cov_Quercus", "cov_Juniperus")
vegeta2<- vegeta
colnames(vegeta2)<-vegeta_col
pca_veg<- prcomp(vegeta2[-1], center = F, scale. = F)

#biplot(pca_env)
metadatas_env<- as.data.frame(pca_veg$x) 
rownames(metadatas_env)<- vegeta$SampleID
metadatas_env<-metadatas_env %>% rownames_to_column(var = "SampleID") %>% inner_join(metadata)

y<-ggordiplots::gg_ordiplot(pca_veg, metadatas_env$Sites, hull = FALSE, 
                            spiders = TRUE,  ellipse = FALSE,   pt.size = 4,
                            plot =FALSE, label = FALSE)
z <- y$plot
a<-z+guides(
  color=guide_legend(title="Sites"))+theme_linedraw() +
  geom_vline(xintercept = 0, linetype = 2) +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2) +
  theme_linedraw()+
          scale_color_carto_d(name = "Sites", palette = "Safe") +
#  scale_color_viridis_d(option ="turbo" )+#color of points 
  theme(axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12), 
        legend.position = "right", 
        legend.box = "vertical",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  ggrepel::geom_label_repel(data=data.frame(pca_veg$rotation) %>%   #arrows
                              rownames_to_column(var = "Feature.ID")%>%
                              slice(-6) %>% 
                              mutate(a=sqrt(PC1^2+PC2^2)) %>% 
                              mutate(PC1=PC1*6, PC2=PC2*6),
                            aes(x=PC1, y=PC2, label=Feature.ID ),
                            segment.colour = NA, col = 'black', 
                            fill= "white",label.padding = 0.1, box.padding = 0.1,
                            fontface="bold.italic", size=4.5) +theme(
                              legend.position = "right")  +
  guides(color = guide_legend(nrow =2 , title = "Sites"))+theme(
    legend.text = element_text(size = 12), legend.title = element_text(size = 14),
    axis.title = element_text(size = 16),
    plot.title = element_text(hjust = 1, size = 12))+
  guides(color = guide_legend(ncol = 1, title = "Sites"))+ geom_vline(xintercept = 0, linetype = 2, color="#88929b") +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2, color="#88929b")+geom_label(
  data = y$df_mean.ord,
  aes(x = x, y = y, label=Group), 
  label.padding = unit(0.1, "lines"),label.size = 0.4,color="white", fill="black",fontface="bold",
)


a

ggsave("pca_veg.png",width =8, height = 5, dpi = 300, plot = a, device = "png")

```


- plotting
```{r, warning=FALSE, message=FALSE}
library(corrplot)
library(rcartocolor)

my_colors <- carto_pal(name = "PinkYl", n = 7)

#png(filename = "cor_both.png", width = 830, height = 430, res = 100)
png(filename = "cor_both.png", width = 3000, height = 1500, res = 300)

par(mfrow=c(1,2))    # set the plotting area into a 1*2 array
corrplot(corss,  method = 'circle', type = 'lower', insig='blank',
         addCoef.col ='black', number.cex = 0.6, tl.cex = 0.8,
         order = 'AOE',diag=FALSE, col = my_colors)
corrplot(corss2,  method = 'circle', type = 'lower', insig='blank',
        addCoef.col ='black', number.cex = 0.5, tl.cex=0.85,
        order = 'AOE', diag=FALSE,col = my_colors)
dev.off()

```

