---
title: "Spatial distance"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Figures 6 and S3 : Spatial distance
- Loading packages
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(broom)
library(geosphere)
library(reshape2)
library(readxl)
library(qiime2R)

source("../Code/functions_betadiv.R")
```


Calculating distances between points

```{r, warning=FALSE, message=FALSE}
coords<- read_csv("../Data/coord.csv")

coords_mat<- coords%>% mutate(P=paste0("P",pol),
                              S=paste0("S", Sitio),
                              T=paste0("T", Transecto)) %>% unite("SampleID", 
  P:T, sep = "") %>% dplyr::select(
    SampleID, Longitude, Latitude) %>% column_to_rownames(
      var = "SampleID") %>% as.matrix() 


distance<- distm(coords_mat)/1000
colnames(distance)<- rownames(coords_mat)
rownames(distance)<- rownames(coords_mat)

distance_complete<- distance

distance[upper.tri(distance)] <- NA 

distance_dm<-melt(as.matrix(distance), varnames = c(
  "SampleID.x", "SampleID.y")) %>% drop_na() %>% filter(!value==0)



```

Loading data of fungi and metadata

```{r, warning=FALSE, message=FALSE}
map<- read.csv("../Data/coord.csv") %>% mutate_at(
    c(1,2,3,7), as.factor) %>% mutate(SampleID= paste0("P",pol, "S", Sitio,"T", Transecto ))
metadata<-read_excel("../Data/Metadatos.xlsx") %>% mutate_if(is.numeric, as.factor)
table_single_micop<- read.delim("../Data/table_micop_single.txt") 
table_paired_micop<- read.delim("../Data/table_micop_paired.txt")
table_qiime2<- data.frame(read_qza("../Data/clustered_table_filter.qza")$data, 
                          check.names = F) %>% t() %>% as.data.frame(
                                ) %>% rownames_to_column(
                            var = "SampleID") %>% separate(
                              SampleID, c(
                                "id_metagenome", "R", "unmap", "Paired"), 
                              sep = "_")%>% inner_join(
                                metadata) %>% dplyr::select(
                                -id_metagenome:-Paired, 
                                -id_sequence:-id_fisicoq, -Sites, 
                                -Names) %>% column_to_rownames(
                                  var="SampleID") %>% t(
                                  ) %>% as.data.frame() %>% mutate_all(as.numeric)

table_fungi<- read.delim("../Data/table_kraken.txt", 
                      row.names = 1, check.names = F) %>% dplyr::select_if( is.numeric)%>% t() %>% as.data.frame() %>% rownames_to_column(
                             var = "id_sequence") %>% separate(
                               ., "id_sequence", c("kraken", "fungi", "id_metagenome", "report", "bracken"),  sep = "_") %>% dplyr::select(-kraken, -fungi, -report, -bracken) %>% full_join( metadata) %>% dplyr::select(-id_sequence:-Transecto, -id_metagenome, -Sites, -id_new, -Names,  -id_fisicoq) %>% column_to_rownames( var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
```

Formatting data as lists and applying functions of beta diversity

```{r, warning=FALSE, message=FALSE}
set.seed(12343)
otu <- list(table_qiime2, table_single_micop, table_paired_micop,  table_fungi)
otu_match<- lapply(otu, otu.match) # matching to map
otu_single<- lapply(otu_match, otu.single) #remove singletons
otu_norm<- lapply(otu_single, otu.norm)#Normalize
bc.dist<- lapply(otu_norm, beta_div_dist_bray)#Calculate Bray-Curtis dissimilarities 
bc.dist2<- lapply(otu_single, beta_div_dist_hill, q=1)#Calculate Horn dissimilarities 
bc.dist.tidy.filt<- lapply(bc.dist, bc.dist.tidy.filter)
bc.dist.tidy.filt2<- lapply(bc.dist2, bc.dist.tidy.filter.hill)

cor_test<- lapply(bc.dist.tidy.filt, cor.b)
lm_test<- lapply(bc.dist.tidy.filt, lm.b)
distances=list(distance_complete, distance_complete, distance_complete, distance_complete)

mantel_test = mapply(mantel.b, bc.dist, distances, SIMPLIFY = FALSE)



cor_test2<- lapply(bc.dist.tidy.filt2, cor.b)
lm_test2<- lapply(bc.dist.tidy.filt2, lm.b)
mantel_test2 = mapply(mantel.b, bc.dist2,distances, SIMPLIFY = FALSE)


stats_qiime2 <- data.frame(
  label = paste0("Mantel: r = ",signif(mantel_test[[1]]$statistic,3), 
                ", p-value = ",   signif(mantel_test[[1]]$signif, 3),                                       "\nRegression: slope = ", signif(lm_test[[1]]$estimate, 3)))

stats_single <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test[[2]]$statistic,3), 
                 ", p-value = ", signif(mantel_test[[2]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test[[2]]$estimate, 3)))

stats_paired <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test[[3]]$statistic,3), 
                 ", p-value = ", signif(mantel_test[[3]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test[[3]]$estimate, 3)))

stats_kraken <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test[[4]]$statistic,3), 
                 ", p-value = ", signif(mantel_test[[4]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test[[4]]$estimate, 3)))


stats_qiime22 <- data.frame(
  label = paste0("Mantel: r = ",signif(mantel_test2[[1]]$statistic,3), 
                ", p-value = ",   signif(mantel_test2[[1]]$signif, 3),                                       "\nRegression: slope = ", signif(lm_test2[[1]]$estimate, 3)))

stats_single2 <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test2[[2]]$statistic,3), 
                 ", p-value = ", signif(mantel_test2[[2]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test2[[2]]$estimate, 3)))

stats_paired2 <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test2[[3]]$statistic,3), 
                 ", p-value = ", signif(mantel_test2[[3]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test2[[3]]$estimate, 3)))

stats_kraken2 <- data.frame(
  label = paste0("Mantel: r = ", signif(mantel_test2[[4]]$statistic,3), 
                 ", p-value = ", signif(mantel_test2[[4]]$signif, 3),
                 "\nRegression: slope = ", signif(lm_test2[[4]]$estimate, 3)))
```


```{r, warning=FALSE, message=FALSE, fig.height=8, fig.width=4}
max.sim<-1
qiime2_data<- bc.dist.tidy.filt[[1]] %>% mutate(Method="GENEIOUS+UNITE")
single_data<- bc.dist.tidy.filt[[2]] %>% mutate(Method="MICOP SINGLE")
paired_data<- bc.dist.tidy.filt[[3]] %>% mutate(Method="MICOP PAIRED")
kraken_data<- bc.dist.tidy.filt[[4]] %>% mutate(Method="KRAKEN2")

qiime2_data2<- bc.dist.tidy.filt2[[1]] %>% mutate(Method="GENEIOUS+UNITE")
single_data2<- bc.dist.tidy.filt2[[2]] %>% mutate(Method="MICOP SINGLE")
paired_data2<- bc.dist.tidy.filt2[[3]] %>% mutate(Method="MICOP PAIRED")
kraken_data2<- bc.dist.tidy.filt2[[4]] %>% mutate(Method="KRAKEN2")

joined_data<- rbind(qiime2_data, single_data, paired_data, kraken_data )
joined_data2<- rbind(qiime2_data2, single_data2, paired_data2, kraken_data2 )

joined_data$Method<- factor(joined_data$Method, levels = c(
  "GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"))
joined_data2$Method<- factor(joined_data2$Method, levels = c(
  "GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"))

ann_text<-data.frame(SpatialDistance=c( 30,30,30,30),
                     Similarity=c(0.8,0.3,0.3,0.3),
                     Distances=c("Spatial Distance (km)", 
                                 "Spatial Distance (km)", 
                                 "Spatial Distance (km)",
                                 "Spatial Distance (km)"),
                     Method=c("GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"),
                     label=c(stats_qiime2$label, 
                             stats_single$label, 
                             stats_paired$label, 
                             stats_kraken$label))

ann_text2<-data.frame(SpatialDistance=c( 30,30,30,30),
                     Similarity=c(0.8,0.3,0.3,0.3),
                     Distances=c("Spatial Distance (km)", 
                                 "Spatial Distance (km)", 
                                 "Spatial Distance (km)",
                                 "Spatial Distance (km)"),
                     Method=c("GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"),
                     label=c(stats_qiime22$label, 
                             stats_single2$label, 
                             stats_paired2$label, 
                             stats_kraken2$label))
                            
ann_text$Method<- factor(ann_text$Method, levels = c(
  "GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"))
ann_text$Distances<- factor(ann_text$Distances,
                            levels = c("Spatial Distance (km)", 
                                       "Environmental Distance", 
                                       "Vegetation Distance"))

ann_text2$Method<- factor(ann_text2$Method, levels = c(
  "GENEIOUS+UNITE", "MICOP SINGLE", "MICOP PAIRED", "KRAKEN2"))
ann_text2$Distances<- factor(ann_text2$Distances,
                            levels = c("Spatial Distance (km)", 
                                       "Environmental Distance", 
                                       "Vegetation Distance"))

d1<-joined_data %>% ggplot(aes(x = SpatialDistance, y =Similarity ))+
  facet_grid(vars(Method), scales = "free_x")+
  geom_point(shape = 16, size = 1, alpha = 0.5, color = "#566573") +
  geom_smooth(method = "lm", color = "black", se = F) +
  ylab("Bray-curtis similarity") +
  ylim(.2, max.sim) +
  theme_linedraw()+theme(legend.position = "none", 
                         axis.text = element_text(size = 12),
                         strip.text = element_text(size = 12, face = "bold.italic"),
                         panel.grid.major = element_line(size = 0.5, 
                                                         linetype = 'solid',
                                                         colour = "#E5E8E8"), 
                         panel.grid.minor = element_line(size = 0.25, 
                                                         linetype = 'solid',
                                                         colour = "#E5E8E8")) +  
  geom_text(data = ann_text,label=ann_text$label, size=3)+xlab("Spatial Distance")



d2<-joined_data2 %>% ggplot(aes(x = SpatialDistance, y =Similarity ))+
  facet_grid(vars(Method), scales = "free_x")+
  geom_point(shape = 16, size = 1, alpha = 0.5, color = "#566573") +
  geom_smooth(method = "lm", color = "black", se = F) +
  ylab("Horn similarity") +
  ylim(.2, max.sim) +
  theme_linedraw()+theme(legend.position = "none", 
                         axis.text = element_text(size = 12),
                         strip.text = element_text(size = 12, face = "bold.italic"),
                         panel.grid.major = element_line(size = 0.5, 
                                                         linetype = 'solid',
                                                         colour = "#E5E8E8"), 
                         panel.grid.minor = element_line(size = 0.25, 
                                                         linetype = 'solid',
                                                         colour = "#E5E8E8")) +  
  geom_text(data = ann_text2,label=ann_text2$label, size=3)+xlab("Spatial Distance")

d1;d2
ggsave("Figure6.spatialdistance-horn_final.pdf",width =4, height = 8, dpi = 300, plot = d2, device = "pdf")
ggsave("FigureS3.spatialdistance-bray_final.png",width =4, height = 8, dpi = 300, plot = d1, device = "png")


```



