---
title: "Metagenomic analysis of the diversity and composition of the fungal communities of forest soils of the transect Iztaccíhuatl-Popocatépetl (PNIP) and La Malinche (PNLM)"
author:
- name: Stephanie Hereira-Pacheco
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r child = './Figure1_maps.Rmd'}
```

```{r child = './FigureS1_alpha_final.Rmd'}
```

```{r child = './Figure3_heatmap_final_mod_groups.Rmd'}
```

```{r child = './Figure4_guilds_final.Rmd'}
```

```{r child = './Figure5andS2_pcoas_final.Rmd'}
```

```{r child = './Figure6_S3_spatial_final.Rmd'}
```

```{r child = './FigureS4andS5_pca_barplotsveg.Rmd'}
```

```{r child = './FigureS6_and_s7_corplot_pca.Rmd'}
```


```{r child = './Figure7and8_S8-S11_cca_rda_finals_nolabels.Rmd'}
```